### ISSUE TITLE
Thread blocked when removing object from AsyncMap

### ISSUE THREAD

**Issue by onesse** [vert-x3/vertx-ignite#37]
Good morning,

In order to place the context, we have 4 servers running continuously, one of them use the feature "sharedData" to store important information. 
```java
vertx.sharedData().<String, String>getClusterWideMap("decoderDevCache", res -> {
	if (res.succeeded()) {
		inGridMap = res.result();
		logger.info("Verticle deployed");
	} else {
		res.cause().printStackTrace();
	}
});
```
But sometimes, when this machine call the async function remove, the thread running our verticle blocks for a long time. It shouldn't be blocked, I don't understand what's going on ? 
Below, you'll find our program output (
```text
2017-03-01 15:55:52 WARNING io.vertx.core.impl.BlockedThreadChecker Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2955 ms, time limit is 2000
2017-03-01 15:55:52 WARNING org.apache.ignite.logger.java.JavaLogger warning Connect timed out (consider increasing 'failureDetectionTimeout' configuration property) [addr=/10.14.0.6:20000, failureDetectionTimeout=10000]
2017-03-01 15:55:53 WARNING io.vertx.core.impl.BlockedThreadChecker Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 3955 ms, time limit is 2000
2017-03-01 15:55:54 WARNING io.vertx.core.impl.BlockedThreadChecker Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 4955 ms, time limit is 2000
2017-03-01 15:55:55 WARNING io.vertx.core.impl.BlockedThreadChecker Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 5957 ms, time limit is 2000
io.vertx.core.VertxException: Thread blocked
	at sun.nio.ch.Net.poll(Native Method)
	at sun.nio.ch.SocketChannelImpl.poll(SocketChannelImpl.java:954)
	at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:110)
	at org.apache.ignite.spi.communication.tcp.TcpCommunicationSpi.createTcpClient(TcpCommunicationSpi.java:2363)
	at org.apache.ignite.spi.communication.tcp.TcpCommunicationSpi.createNioClient(TcpCommunicationSpi.java:2140)
	at org.apache.ignite.spi.communication.tcp.TcpCommunicationSpi.reserveClient(TcpCommunicationSpi.java:2034)
	at org.apache.ignite.spi.communication.tcp.TcpCommunicationSpi.sendMessage0(TcpCommunicationSpi.java:1970)
	at org.apache.ignite.spi.communication.tcp.TcpCommunicationSpi.sendMessage(TcpCommunicationSpi.java:1936)
	at org.apache.ignite.internal.managers.communication.GridIoManager.send(GridIoManager.java:1304)
	at org.apache.ignite.internal.managers.communication.GridIoManager.send(GridIoManager.java:1373)
	at org.apache.ignite.internal.processors.cache.GridCacheIoManager.send(GridCacheIoManager.java:831)
	at org.apache.ignite.internal.processors.cache.GridCacheIoManager.send(GridCacheIoManager.java:980)
	at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridNearAtomicSingleUpdateFuture.mapSingle(GridNearAtomicSingleUpdateFuture.java:461)
	at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridNearAtomicSingleUpdateFuture.map(GridNearAtomicSingleUpdateFuture.java:569)
	at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridNearAtomicSingleUpdateFuture.mapOnTopology(GridNearAtomicSingleUpdateFuture.java:441)
	at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridNearAtomicAbstractUpdateFuture.map(GridNearAtomicAbstractUpdateFuture.java:207)
	at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache$23.apply(GridDhtAtomicCache.java:1050)
	at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache$23.apply(GridDhtAtomicCache.java:1048)
	at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.asyncOp(GridDhtAtomicCache.java:711)
	at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.removeAsync0(GridDhtAtomicCache.java:1048)
	at org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridDhtAtomicCache.getAndRemoveAsync(GridDhtAtomicCache.java:616)
	at org.apache.ignite.internal.processors.cache.IgniteCacheProxy.getAndRemove(IgniteCacheProxy.java:1356)
	at io.vertx.spi.cluster.ignite.impl.AsyncMapImpl.lambda$remove$5(AsyncMapImpl.java:77)
	at io.vertx.spi.cluster.ignite.impl.AsyncMapImpl$$Lambda$170/239295063.accept(Unknown Source)
	at io.vertx.spi.cluster.ignite.impl.AsyncMapImpl.executeWithTimeout(AsyncMapImpl.java:112)
	at io.vertx.spi.cluster.ignite.impl.AsyncMapImpl.execute(AsyncMapImpl.java:106)
	at io.vertx.spi.cluster.ignite.impl.AsyncMapImpl.remove(AsyncMapImpl.java:77)
	at io.vertx.core.shareddata.impl.SharedDataImpl$WrappedAsyncMap.remove(SharedDataImpl.java:209)
	at fr.fluxon.network.service.cache.handlers.InvalidateDecoderCacheHandler.handle(InvalidateDecoderCacheHandler.java:33)
	at fr.fluxon.network.service.cache.VerticleDecoderCache.executeWithHandler(VerticleDecoderCache.java:146)
	at fr.fluxon.network.service.cache.VerticleDecoderCache.lambda$registerMessageHandler$5(VerticleDecoderCache.java:130)
	at fr.fluxon.network.service.cache.VerticleDecoderCache$$Lambda$100/1803191682.handle(Unknown Source)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:191)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:503)
	at io.vertx.core.eventbus.impl.EventBusImpl$$Lambda$137/709849356.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:316)
	at io.vertx.core.impl.ContextImpl$$Lambda$22/2037757743.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)

```
On InvalidateDecoderCacheHandler.java:33 : 
```java
inGridMap.remove(device.getDevAddr(), rmRes -> {
	if (rmRes.failed()) {
		rmRes.cause().printStackTrace();
	}
});
```

**Comment by agura** [comment]
It seems that you have network problems during connection creation:

```
at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:110)
at org.apache.ignite.spi.communication.tcp.TcpCommunicationSpi.createTcpClient(TcpCommunicationSpi.java:2363)
```

Could you please provide more details about your configuration (NAT, cotainers, smth else)?

**Comment by onesse** [comment]
To give you more details : 
- 3 machines with public IP in the same datacenter (no containers)
- SSL connection enabled between them 
- one machine is storing data in the "inGridMap"
- 3..3.3 vertx version

I pretty sure it's a configuration problem (JVM or ignite)  (I'm a newbie) 

Since my last message I did not experienced this bug again but another one very annoying (i'll open a new issue for it) that can be the root of this problem. 

Below the JVM arguments
```bash
-server -Xmx512m -Xms512m -XX:+UseParNewGC  -XX:+UseConcMarkSweepGC  -XX:+UseTLAB  -XX:NewSize=128m  -XX:MaxNewSize=128m  -XX:MaxTenuringThreshold=0  -XX:SurvivorRatio=1024  -XX:+UseCMSInitiatingOccupancyOnly  -XX:CMSInitiatingOccupancyFraction=60 -XX:+DisableExplicitGC
```

And my ignite configuration file
```xml
<?xml version="1.0" encoding="UTF-8"?>

<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:util="http://www.springframework.org/schema/util"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
                           http://www.springframework.org/schema/beans/spring-beans.xsd
                           http://www.springframework.org/schema/util
                           http://www.springframework.org/schema/util/spring-util.xsd">

    <bean class="org.apache.ignite.configuration.IgniteConfiguration">

        <property name="communicationSpi">
            <bean class="org.apache.ignite.spi.communication.tcp.TcpCommunicationSpi">
                <property name="socketWriteTimeout" value="4000"/>
                <!-- Override local port. -->
                <property name="localPort" value="20000"/>
                <property name="LocalPortRange" value="1"/>
            </bean>
        </property>

        <!-- Explicitly configure TCP discovery SPI to provide list of initial nodes. -->
        <property name="discoverySpi">
            <bean class="org.apache.ignite.spi.discovery.tcp.TcpDiscoverySpi">
                <!-- Override local port. -->
                <property name="localPort" value="20100"/>
                <property name="LocalPortRange" value="1"/>

                <property name="ipFinder">
                    <bean class="org.apache.ignite.spi.discovery.tcp.ipfinder.vm.TcpDiscoveryVmIpFinder">
                        <property name="addresses">
                            <list>
                                <!--In distributed environment, replace with actual host IP address.-->
                                <value>HOST1</value>
                                <value>HOST1</value>
                                <value>HOST2</value>
                            </list>
                        </property>
                    </bean>
                </property>
            </bean>
        </property>

        <property name="sslContextFactory">
            <bean class="org.apache.ignite.ssl.SslContextFactory">
                <property name="keyStoreFilePath" value="myFile1.jks"/>
                <property name="keyStorePassword" value="myPass1"/>
                <property name="trustStoreFilePath" value="myFile2.jks"/>
                <property name="trustStorePassword" value="myPass2"/>
                <property name="trustManagers">
                    <bean class="org.apache.ignite.ssl.SslContextFactory" factory-method="getDisabledTrustManager"/>
                </property>
            </bean>
        </property>

        <property name="cacheConfiguration">
            <!--<list>-->
                <bean class="org.apache.ignite.configuration.CacheConfiguration">
                    <property name="name" value="*"/>
                    <property name="cacheMode" value="PARTITIONED"/>
                    <property name="atomicityMode" value="ATOMIC"/>
                    <property name="atomicWriteOrderMode" value="PRIMARY"/>
                    <property name="swapEnabled" value="false"/>
                    <property name="backups" value="1"/>
                    <property name="memoryMode" value="ONHEAP_TIERED"/>
                </bean>
        </property>

        <property name="includeEventTypes">
            <list>
                <util:constant static-field="org.apache.ignite.events.EventType.EVT_CACHE_OBJECT_REMOVED"/>
            </list>
        </property>

        <!-- Logging configuration. -->
        <property name="gridLogger">
            <bean class="org.apache.ignite.logger.java.JavaLogger">
                <constructor-arg type="java.util.logging.Logger">
                    <bean class="java.util.logging.Logger">
                        <constructor-arg type="java.lang.String" value="global"/>
                    </bean>
                </constructor-arg>
            </bean>
        </property>

        <property name="metricsLogFrequency" value="0"/>

    </bean>
</beans>
```

**Comment by agura** [comment]
@onesse At first look configuration is ok. Could you check connectivity without SSL? Also please check that  there are free open ports for connections because 20000 and 20010 ports are responsible only for connection accepting. And try to find connect related exceptions in logs (not only Vert.x block checker warnings).

**Comment by agura** [comment]
@onesse Is this issue still actual or I can close it?

**Comment by onesse** [comment]
@agura I tried to reproduce it without success !
You can close it. Thanks :)
