### ISSUE TITLE
IgniteClusterManager.join may throw java.lang.IllegalStateException: Result is already complete: succeeded

### ISSUE THREAD

**Issue by emogua** [vert-x3/vertx-ignite#76]
fut.complete(); is called twice in line 288 and line 297.
It seems like does not effect normal flow. But I'm not sure about that.
I think the last call should be removed.

**Comment by emogua** [comment]
Full stack trace:

8月 09, 2019 5:50:06 下午 io.vertx.core.impl.ContextImpl
严重: Unhandled exception
java.lang.IllegalStateException: Result is already complete: succeeded
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:95)
	at io.vertx.spi.cluster.ignite.IgniteClusterManager.lambda$null$4(IgniteClusterManager.java:288)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by NavidMitchell** [comment]
I am seeing this same error every time I start a cluster node.

**Comment by emogua** [comment]
I'm afraid this lib is dead, I implement it by myself...

> I am seeing this same error every time I start a cluster node.

**Comment by NavidMitchell** [comment]
@emogua Hopefully they will pull.. :)

**Comment by vietj** [comment]
@emogua you can become contributor of this project if you want

**Comment by NavidMitchell** [comment]
@vietj I would be happy to become a contributor. Thank You :)

**Comment by vietj** [comment]
how about starting upgrading Ignite version and having this project running in Travis CI ?

**Comment by NavidMitchell** [comment]
Yes sure that is something I can work on.
